@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NTI4MjAxNTJ9._URsEohi4wabj-VtnTD0nWm3W9kdpHd-Q9rV1AU-mIQ
###
GET http://localhost:3000/rec_areas.json
###
GET http://localhost:3000/peaks.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

###
GET http://localhost:3000/peaks/15.json
###
GET http://localhost:3000/rec_areas/145.json
###
GET http://localhost:3000/activities.json
###
GET http://localhost:3000/activities/37.json

### Peak Reviews
GET http://localhost:3000/peak_reviews.json
###
GET http://localhost:3000/peak_reviews/6.json
###
POST http://localhost:3000/peak_reviews.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "peak_id" : 10,
  "review" : "Weather turned towards the summit, but we persevered and made it back down before the worst of it. Immaculate views."
}
###
PATCH http://localhost:3000/peak_reviews/5
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "review" : "As long as you keep your legs moving - you'll make it to the top!"
}
###
DELETE http://localhost:3000/peak_reviews/7
Authorization: Bearer {{jwt}}
Content-Type: application/json

### Rec Area Reviews
GET http://localhost:3000/rec_area_reviews.json
###
GET http://localhost:3000/rec_area_reviews/1.json
###
POST http://localhost:3000/rec_area_reviews
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "rec_area_id" : 146,
  "review" : "I've been to better places in my years, but it got the job done."
}
###
PATCH http://localhost:3000/rec_area_reviews/1
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "review" : "This camp area was amazing. Bathrooms easily accessible, and most of all - it was easy to find! We will definitely keep this place on our list!" 
}

###
DELETE http://localhost:3000/rec_area_reviews/5
Authorization: Bearer {{jwt}}
Content-Type: application/json

### User actions###
GET http://localhost:3000/users/profile.json
Authorization: Bearer {{jwt}}
###
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Travis",
  "email": "Travis@gmail.com",
  "password": "password",
  "password_confirmation": "password",
  "image_url" : ""
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "Edmund@gmail.com",
  "password": "password"
}