@jwt = "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTExOTU0OTd9.OgOYNrSX1wN8f0bTQiip2YL6OwfJLreUtDTywgg54fM" 
###
GET http://localhost:3000/rec_areas
###
GET http://localhost:3000/peaks.json
###
GET http://localhost:3000/peaks/2.json
###
GET http://localhost:3000/rec_areas/2.json
###
GET http://localhost:3000/activities.json
###
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Travis",
  "email": "Travis@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "Travis@gmail.com",
  "password": "password"
}